---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create container
  lxc_container:
    name: "{{ item.name }}"
    template: "download"
    state: stopped
    backing_store: "dir"
    template_options: >
      --dist {{ item.distro }}
      --release {{ item.release }}
      --arch {{ item.arch }}
  register: cache_download
  retries: 3
  delay: 10
  until: cache_download|success
  with_items: lxc_image_meta
  tags:
    - repo-lxc-cache
    - repo-lxc-cache-download

- name: Create meta directory
  file:
    path: "/var/lib/lxc/{{ item.name }}/meta"
    state: "directory"
  with_items: lxc_image_meta
  tags:
    - repo-lxc-cache
    - repo-lxc-cache-dirs
